JuliaGeometry/CoordinateTransformations.jl

README.md, REQUIRE, src/CoordinateTransformations.jl, src/commontransformations.jl, src/coordinatesystems.jl, src/core.jl, test/commontransformations.jl, test/coordinatesystems.jl, test/core.jl
`AbstractTransformation{InType,OutType}` has been simplified to
`Transformation`. Input and output types are no-longer constrained.
Closes #1.
=> Simplified AbstractTransformation

src/CoordinateTransformations.jl, src/commontransformations.jl, src/core.jl, test/commontransformations.jl, test/runtests.jl
We implement some abstract and concrete types of Affine and linear transformations (as well as translations). A quick overview: 
* A `LinearTransformation` is more-or-less a wrapper for a matrix or matrix-like object which can be chained with `compose` and called to result in matrix multiplication.
* A `Translation` is a similar wrapper for adding a vector or vector-like object.
* An `AffineTransformation` has both of these - first multiplying by the matrix, then adding the vector. This is our canonical choice, but it is well documented.
* These compose together in sensible ways, e.g. by turning two Affine transformations into just one.
There are also related functions such as `translation_vector()` and `transformation_matrix()` for extracting the parameters from an …
=> Affine transforms

REQUIRE, src/CoordinateTransformations.jl, src/affine.jl, src/core.jl, test/affine.jl
Some minor fixes for julia-0.6 deprecations and addition of \circ to Base.
Fixes #26
=> Julia 0.6 fixes

.travis.yml, REQUIRE, appveyor.yml, src/CoordinateTransformations.jl, src/affine.jl, src/coordinatesystems.jl, src/core.jl, src/perspective.jl
I'm trying to update a bunch of packages for v0.7 compatibility. 
This package isn't seeing a lot of action relevant to v0.5.
=> Update syntax to v0.6+, drop v0.5 support

REQUIRE, src/coordinatesystems.jl
Fixes the last deprecation warning on 0.7. 
Also, could you please tag a new release after this is merged so that we'll have an 0.7-compatible release?
=> atan2(y, x) -> atan(y, x)

REQUIRE, src/affine.jl, test/affine.jl
This came up in #37. The performance regression discussed in #37 does not exist anymore in julia 0.7.
It is amazing, all intermediate objects (LinearMap, Translation...) are completly optimized out!
```julia
using CoordinateTransformations
using StaticArrays
function apply_lt(trans::AffineMap, x)
l = LinearMap(trans.linear)
t = Translation(trans.translation)
t(l(x))
end
m = @SMatrix randn(3,3)
v = @SVector randn(3)
am = AffineMap(m,v)
@code_warntype apply_lt(am,v)
```
```
Body::SArray{Tuple{3},Float64,1,3}
│╻       getproperty5 1 ── %1  = (Base.getfield)(trans, :linear)::SArray{Tuple{3,3},Float64,2,9}
│╻       getproperty6 │    %2  = (Base.getfield)(trans, :translation)::SArray{Tuple{3},Float64,1,3}
│╻╷╷╷╷╷  LinearMap7 │    %3  = (Base.getfield)(%1, :data)::NTuple{9,Float64}
││╻       * …
```
=> Reduce AffineMap application to Linear and Translation

src/coordinatesystems.jl
- Replaced `sqrt(x[1]*x[1]+x[2]*x[2])` with `hypot(x[1],x[2])` (and 3arg equivalent)
- Replaced `atan` with fraction with 2 argument version in Cartesian <-> Spherical
This closes #57
=> Use hypot for the radial coordinate

Project.toml, src/coordinatesystems.jl, test/coordinatesystems.jl, test/runtests.jl
- Add separate type parameter for the angle
- Promote types for combinations of AbstractFloat and Integer
I did not consider `<:Number` because I didn't know how to do it without getting a stack overflow and also because Unitful subtypes `Number` and promoting to a common type is exactly the opposite of what this PR is trying to do.
I tried to cover the most common cases with the tests. Let me know what you think of this.
This closes #58
=> Unitful compatibility

.github/workflows/compathelper.yml
Note that with the default settings, CI will not be triggered on CompatHelper PRs. As explained [here](https://github.com/bcbi/CompatHelper.jl#12-set-up-the-ssh-deploy-key-optional) ssh deploy keys would be required for that.
=> Add CompatHelper

src/affine.jl, src/core.jl, test/affine.jl
`OffsetArrays.center` is added in https://github.com/JuliaArrays/OffsetArrays.jl/pull/242, and I think it makes sense to remove `ImageTransformations.center` in favor of `OffsetArrays.center`
```julia
center(img::AbstractArray{T,N}) where {T,N} = SVector{N}(map(_center, axes(img)))
_center(ind::AbstractUnitRange) = (first(ind)+last(ind))/2
```
The only reason that `SVector` is used here is because `CoordinateTransformations.recenter` requires `AbstractVector` input, I relax this constrain in this PR so that `OffsetArrays.center` can be a drop-in replacement for `ImageTransformations.center` (if we ignore the integer rounding differences).
=> recenter: accept `origin::Tuple`

.github/workflows/ci.yml, docs/src/note.txt, test/coordinatesystems.jl, test/runtests.jl
Those tests once marked broken (https://github.com/JuliaGeometry/CoordinateTransformations.jl/pull/60) seem to pass now.
=> Fix testing

src/affine.jl, test/affine.jl
`vecnorm` was changed to `norm` in Julia 1.0, and the equivalent `linear` part of a `Translation` is the identity.
=> Fix equality/isapprox comparisons between different affine subtypes

src/coordinatesystems.jl, test/coordinatesystems.jl
This adds a simple Polar() convenience constructor that accepts an AbstractVector.
The constructor is mentioned in the README file but doesn't exist. 
This closes issue #83.
=> Added convenience Polar() constructor

README.md, src/affine.jl, test/affine.jl
Given a set of point pairs `from => to`, compute the affine
transformation that best reproduces the observed mapping.
Closes #30
=> Construct affine transforms from point-pairs

.gitignore, docs/Project.toml, docs/make.jl, docs/src/api.md, docs/src/index.md, src/affine.jl, src/coordinatesystems.jl, src/perspective.jl
- Add documentation website through Documenter.jl
- Fix docstrings so that they get picked up by Documenter.jl
Note: the documentation site isn't currently deployed, it's only for local building. A future PR can add in the functionality for deploying.
=> Documentation website and docstrings

.github/workflows/ci.yml, docs/make.jl, docs/src/api.md, docs/src/index.md, src/affine.jl, src/coordinatesystems.jl, src/core.jl, test/coordinatesystems.jl, test/runtests.jl
- Add docstrings
- Refactor doc pages
- Enable CI documentation build
- Tweak doctest setup
=> Deploy documentation

src/affine.jl
Delegate output to print(), which can handle larger arrays better than string interpolation
=> Make Base.show() output more petite

.github/workflows/ci.yml, Project.toml, docs/Project.toml, docs/src/index.md
Added (presumably accidentally) in a0b7026
CC @sjkelly
=> Remove JET from Project.toml, get tests passing, bump to Julia 1.10

README.md, docs/src/api.md, docs/src/index.md, src/CoordinateTransformations.jl, src/kabsch.jl, test/affine.jl
Given two sets of points, this constructs rigid (rotation + translation) and similarity (rotation, translation, and scaling) transformations that align the first set to the second in the least-squares sense. Similar to #87, but with constraints on the nature of the transformation.
Co-authored by @tmcgrath325
=> Construct similarity transformations from point-pairs

README.md
We were also missing a deploy key, so I replaced DOCUMENTER_KEY and added the corresponding deploy key.
=> Add doc badges to README
